services:
  - type: web
    name: gemini-clone-backend
    region: singapore
    runtime: node
    rootDir: ./backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
